apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
        - name: jenkins-demo
          image: joseantony07/jenkins_demo:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  namespace: jenkins
spec:
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer


# kubectl apply -f jenkins_demo_kubernetes.yaml
# kubectl delete -f jenkins_demo_kubernetes.yaml
# minikube service jenkins-demo -n jenkins
# minikube dashboard
